$modelname		"@vehicles/hetzer/wheel.mdl"
$cdmaterials	"models/@vehicles/hetzer/"
$surfaceprop	metal
$staticprop
$sequence idle	"wheel.smd"
$body mainbody	"wheel.smd"
$texturegroup	"skins"
{
	{ "wheel" }
	{ "wheel1" }
	{ "wheel2" }
	{ "wheel3" }
	{ "wheel4" }
	{ "wheel5" }
	{ "wheel6" }
	{ "wheel7" }
	{ "wheel8" }
	{ "wheelMetal" }
	{ "wheelOriginal" }
}
$collisionmodel	"wheel.smd" { $concave }



